const events = [];
const BETS_KEY = 'betting-lab-bets';
const statuses = ['FRESH','STALE','DELAYED','MISSING','CONFLICTING','NO_CALL','UNAVAILABLE'];
const $ = id => document.getElementById(id);
function esc(value) { const node = document.createElement('span'); node.textContent = String(value); return node.innerHTML; }
function unavailableCard(sport, competition, reason) { return {sport, competition, name:'Keine Live-Daten verfügbar', status:'UNAVAILABLE', reason, source:'Keine bestätigte Quelle', id:'unknown'}; }
function catalog(feed=[]) { return feed.length ? feed.map(e => ({...e, name:`${e.home} · ${e.away}`, status:'FRESH', reason:`${e.markets.length} Markt-/Buchmacherangebote`, source:'The Odds API'})) : [
  unavailableCard('Fußball','Länderspiele','Provider und Lizenz für diesen Datenabruf nicht konfiguriert.'),
  unavailableCard('Fußball','Bundesliga','Provider und Lizenz für diesen Datenabruf nicht konfiguriert.'),
  unavailableCard('Fußball','2. Bundesliga','Provider und Lizenz für diesen Datenabruf nicht konfiguriert.'),
  unavailableCard('Fußball','3. Liga','Provider und Lizenz für diesen Datenabruf nicht konfiguriert.'),
  unavailableCard('Fußball','Große europäische Ligen','Provider und Lizenz für diesen Datenabruf nicht konfiguriert.'),
  unavailableCard('Volleyball','Nicht konfiguriert','Coverage-Test fehlt; keine Fußball-/NFL-Daten übertragen.'),
  unavailableCard('NFL','NFL','Live-Quotenquelle nicht konfiguriert; nflverse liefert keine Live-Quoten.'),
  unavailableCard('Scorer','Scorer-Märkte','Rolle und Einsatzwahrscheinlichkeit nicht belastbar verfügbar.')
]; }
function renderSummary(list) { const counts = Object.fromEntries(statuses.map(s => [s,0])); list.forEach(e => counts[e.status]++); $('summary').innerHTML = statuses.map(s => `<div class="chip"><strong>${counts[s]}</strong><span>${s}</span></div>`).join(''); }
function oddsRows(e) { return (e.markets || []).slice(0,12).map(m => `<tr><td>${esc(m.bookmaker)}</td><td>${esc(m.market)}</td><td>${(m.outcomes||[]).map(o => `${esc(o.name)} <b>${Number(o.price).toFixed(2)}</b>${o.point==null?'':` (${esc(o.point)})`}`).join(' · ')}</td></tr>`).join('') || '<tr><td colspan="3">Keine Marktangebote für dieses Event.</td></tr>'; }
function renderDetail(e) { $('detail').innerHTML = `<h2>${esc(e.name)}</h2><span class="badge ${e.status==='FRESH'?'fresh':'unavailable'}">${esc(e.status)}</span><dl><div><dt>Sport / Wettbewerb</dt><dd>${esc(e.sport)} · ${esc(e.competition)}</dd></div><div><dt>Start</dt><dd>${esc(e.start)}</dd></div><div><dt>Event-ID</dt><dd>${esc(e.id)}</dd></div><div><dt>Quelle</dt><dd>The Odds API · Abrufzeit im Kopf</dd></div></dl><h3>Quoten</h3><div class="table-wrap"><table><thead><tr><th>Buchmacher</th><th>Markt</th><th>Ausgänge / Quote</th></tr></thead><tbody>${oddsRows(e)}</tbody></table></div><p class="reason">${esc(e.reason || 'Live-Quoten vorhanden. Eigene Modellwahrscheinlichkeit noch nicht verifiziert.')}</p><p><strong>NO_CALL · NO BET</strong><br>Keine eigene faire Quote ohne unabhängiges Modell. Marktquote bleibt sichtbar.</p>`; }
function render(list) { renderSummary(list); $('count').textContent = `${list.length} Katalogeinträge`; $('events').innerHTML = list.map((e,i) => `<article class="card" tabindex="0" data-index="${i}"><div class="card-head"><span class="badge ${e.status==='FRESH'?'fresh':'unavailable'}">${esc(e.status)}</span><span class="meta">${esc(e.sport)}</span></div><h3>${esc(e.name || e.competition)}</h3><p class="reason">${esc(e.reason || `${e.markets.length} Quotenangebote · Start ${e.start}`)}</p><div class="metrics"><div class="metric"><b>${e.markets?.length || 0}</b><small>Marktangebote</small></div><div class="metric"><b>${e.markets?.[0]?.outcomes?.[0]?.price ? Number(e.markets[0].outcomes[0].price).toFixed(2) : '—'}</b><small>Beste sichtbare Quote</small></div><div class="metric"><b>NO_CALL</b><small>Eigenes Modell</small></div><div class="metric"><b>${e.start ? esc(e.start.slice(11,16)) : '—'}</b><small>Start UTC</small></div></div></article>`).join(''); document.querySelectorAll('.card').forEach(card => { const select=()=>renderDetail(list[card.dataset.index]); card.addEventListener('click',select); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ') {e.preventDefault();select();}}); }); $('global-status').textContent = 'Keine Live-Daten geladen'; }
let liveEvents = [];
function applyFilters() { const sport=$('sport-filter').value, comp=$('competition-filter').value; render(catalog(liveEvents).filter(e=>(sport==='all'||e.sport===sport)&&(comp==='all'||e.competition===comp))); }
function fillCompetitions() { $('competition-filter').innerHTML = '<option value="all">Alle Wettbewerbe</option>'+[...new Set(catalog(liveEvents).map(e=>e.competition))].map(e=>`<option>${esc(e)}</option>`).join(''); }
function refreshOdds() { return fetch('/api/odds').then(response => response.json()).then(data => { liveEvents=data.status==='available' ? data.events : []; fillCompetitions(); applyFilters(); $('odds-status').textContent=data.status==='available' ? `VERFÜGBAR · ${data.events.length} Events · ${data.retrieved_at}` : `UNAVAILABLE · ${data.reason || 'Quelle nicht bestätigt'}`; }); }
$('sport-filter').addEventListener('change',applyFilters); $('competition-filter').addEventListener('change',applyFilters); $('refresh').addEventListener('click',refreshOdds); applyFilters();
function bets() { try { const value = JSON.parse(localStorage.getItem(BETS_KEY) || '[]'); return Array.isArray(value) ? value : []; } catch (_) { return []; } }
function renderBetStats() { const list = bets(), stake = list.reduce((sum, bet) => sum + bet.stake, 0), wins = list.filter(b => b.result === 'win').length, losses = list.filter(b => b.result === 'loss').length; $('bet-stats').innerHTML = `<div><b>${list.length}</b><small>Einträge</small></div><div><b>${stake.toFixed(2)} €</b><small>Gesamteinsatz</small></div><div><b>${wins}</b><small>Gewonnen</small></div><div><b>${losses}</b><small>Verloren</small></div>`; $('journal').innerHTML = list.length ? list.map(b => `<tr><td>${esc(b.date)}</td><td>${esc(b.sport)}</td><td>${b.stake.toFixed(2)} €</td><td>${esc(b.result)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty">Noch keine lokalen Einträge.</td></tr>'; $('bet-chart').style.backgroundSize = list.length ? `100% ${Math.max(20, 100 - Math.min(80, stake))}%` : '100% 100%'; }
$('bet-form').addEventListener('submit', event => { event.preventDefault(); const bet = {date:$('bet-date').value, sport:$('bet-sport').value.trim(), stake:Number($('bet-stake').value), result:$('bet-result').value}; if (!bet.date || !bet.sport || !Number.isFinite(bet.stake) || bet.stake <= 0) return; localStorage.setItem(BETS_KEY, JSON.stringify([...bets(), bet])); $('bet-message').textContent = 'Lokal gespeichert. Keine Übertragung.'; event.target.reset(); renderBetStats(); });
renderBetStats();
refreshOdds().catch(() => { $('odds-status').textContent = 'UNAVAILABLE · Statusabruf fehlgeschlagen'; });
