const BETS_KEY = 'betting-lab-bets';
const statuses = ['PAPER', 'NO_CALL', 'UNAVAILABLE'];
const $ = id => document.getElementById(id);
let liveEvents = [];
let bettingState = null;

function esc(value) { const node = document.createElement('span'); node.textContent = String(value ?? 'UNAVAILABLE'); return node.innerHTML; }
function sportLabel(event) { return event.competition === 'NFL' ? 'NFL' : 'Fußball'; }
function berlin(iso) { if (!iso || iso === 'UNAVAILABLE') return 'UNAVAILABLE'; try { return new Intl.DateTimeFormat('de-DE', {timeZone:'Europe/Berlin', dateStyle:'short', timeStyle:'short'}).format(new Date(iso)) + ' Uhr'; } catch (_) { return iso; } }
function quoteData(event) { const probability=Number(event.model_probability), market=Number(event.market_price), fair=Number(event.fair_quote), expected=Number(event.expected_value); if (!Number.isFinite(probability) || probability <= 0 || probability >= 1 || !Number.isFinite(market) || market <= 1 || !Number.isFinite(fair) || fair <= 1) return null; return {probability, market, fair, expected}; }
function quoteText(event) { const quote=quoteData(event); return quote ? `Fair ${quote.fair.toFixed(2)} · Markt ${quote.market.toFixed(2)} · EV ${Number.isFinite(quote.expected) ? (quote.expected * 100).toFixed(1) + '%' : 'UNAVAILABLE'}` : 'NO_CALL · Modellwahrscheinlichkeit fehlt'; }
function classFor(status) { return status === 'PAPER' ? 'paper' : status === 'NO_CALL' ? 'no-call' : 'unavailable'; }
function catalog(feed=[]) { return feed.map(event => ({...event, name:`${event.home} · ${event.away}`, displaySport:sportLabel(event), source:'The Odds API'})); }
function renderSummary(list) { const counts=Object.fromEntries(statuses.map(status => [status, 0])); list.forEach(event => { counts[event.status] = (counts[event.status] || 0) + 1; }); $('summary').innerHTML=statuses.map(status => `<div class="chip"><strong>${counts[status] || 0}</strong><span>${status}</span></div>`).join(''); }
function oddsRows(event) { return (event.markets || []).slice(0, 12).map(market => `<tr><td>${esc(market.bookmaker)}</td><td>${esc(market.market)}</td><td>${(market.outcomes || []).map(outcome => `${esc(outcome.name)} <b>${Number(outcome.price).toFixed(2)}</b>${outcome.point == null ? '' : ` (${esc(outcome.point)})`}`).join(' · ')}</td></tr>`).join('') || '<tr><td colspan="3">Keine Marktangebote.</td></tr>'; }
function renderDetail(event) { const quote=quoteData(event); $('detail').innerHTML=`<h2>${esc(event.name)}</h2><span class="badge ${classFor(event.status)}">${esc(event.status)}</span><dl><div><dt>Sport / Wettbewerb</dt><dd>${esc(event.displaySport)} · ${esc(event.competition)}</dd></div><div><dt>Start Berlin</dt><dd>${esc(berlin(event.start))}</dd></div><div><dt>Beste Quote</dt><dd>${quote ? quote.market.toFixed(2) : 'UNAVAILABLE'} · ${esc(event.best_bookmaker)}</dd></div><div><dt>Modellstatus</dt><dd>${esc(event.status)}</dd></div></dl><h3>Paper-Kandidat</h3><p class="quote-line"><strong>${esc(event.tip_text || quoteText(event))}</strong></p><p class="reason">${esc(event.rationale)}</p><h3>Quoten</h3><div class="table-wrap"><table><thead><tr><th>Buchmacher</th><th>Markt</th><th>Ausg&auml;nge / Quote</th></tr></thead><tbody>${oddsRows(event)}</tbody></table></div><p><strong>PAPER ONLY · NO CASH</strong><br>Kein unabh&auml;ngiges Vorhersagemodell. Erst nach Backtest bewerten.</p>`; }
function render(list) { renderSummary(liveEvents); $('count').textContent = `${list.length} Paper-Kandidaten`; $('events').innerHTML=list.length ? list.map((event,index) => `<article class="card" tabindex="0" data-index="${index}"><div class="card-head"><span class="badge ${classFor(event.status)}">${esc(event.status)}</span><span class="meta">${esc(event.displaySport)}</span></div><h3>${esc(event.name)}</h3><p class="tip-line"><strong>Paper:</strong> ${esc(event.selection || event.tip_text || 'NO_CALL')}</p><p class="reason">${esc(event.rationale)}</p><div class="metrics"><div class="metric"><b>${event.markets?.length || 0}</b><small>Marktangebote</small></div><div class="metric"><b>${esc(quoteText(event))}</b><small>Bewertung</small></div><div class="metric"><b>${esc(event.best_bookmaker)}</b><small>Beste Quote</small></div><div class="metric"><button type="button" class="paper-save" data-index="${index}">Paper vormerken</button></div></div></article>`).join('') : '<div class="notice"><strong>Keine Paper-Kandidaten.</strong><br>Quoten sind vorhanden, aber kein marktbasierter Kandidat überschreitet aktuelle Mindestgrenzen. Das ist kein Profitnachweis.</div>';
  document.querySelectorAll('#events .card').forEach(card => { const select=()=>renderDetail(list[Number(card.dataset.index)]); card.addEventListener('click', event => { if (!event.target.closest('button')) select(); }); card.addEventListener('keydown', event => { if ((event.key === 'Enter' || event.key === ' ') && !event.target.closest('button')) { event.preventDefault(); select(); } }); });
  document.querySelectorAll('.paper-save').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); savePaperCandidate(list[Number(button.dataset.index)], button); }));
  $('global-status').textContent = bettingState?.feed?.freshness === 'stale' ? 'Snapshot veraltet · Timer prüfen' : liveEvents.length ? `${liveEvents.length} Events · Paper-Kandidaten gefiltert` : 'Keine bestätigten Live-Daten';
}
function playable(event) { return event.status === 'PAPER' && Number(event.expected_value) > 0; }
function applyFilters() { const sport=$('sport-filter').value, competition=$('competition-filter').value; const candidates=catalog(liveEvents).filter(playable).filter(event => (sport === 'all' || event.displaySport === sport) && (competition === 'all' || event.competition === competition)); render(candidates); }
function renderMarkets(feed) { const rows=feed.flatMap(event => (event.markets || []).slice(0, 4).map(market => `<tr><td>${esc(sportLabel(event))}</td><td>${esc(event.competition)}</td><td>${esc(market.market)}</td><td>${esc(event.status || 'NO_CALL')}</td><td>The Odds API</td></tr>`)); $('markets').innerHTML=rows.length ? rows.slice(0,100).join('') : '<tr><td colspan="5" class="empty">Keine verifizierten Märkte verfügbar.</td></tr>'; }
function fillCompetitions() { $('competition-filter').innerHTML='<option value="all">Alle Wettbewerbe</option>'+[...new Set(liveEvents.map(event => event.competition))].map(value => `<option>${esc(value)}</option>`).join(''); }
function renderPaperMetrics(metrics) { $('paper-metrics').innerHTML=`<div><b>${metrics.open_bets}</b><small>Offen</small></div><div><b>${metrics.settled_bets}</b><small>Ausgewertet</small></div><div><b>${metrics.profit_cents == null ? 'UNAVAILABLE' : (metrics.profit_cents / 100).toFixed(2) + ' €'}</b><small>Paper-P/L</small></div><div><b>${metrics.roi == null ? 'UNAVAILABLE' : (metrics.roi * 100).toFixed(1) + '%'}</b><small>ROI</small></div><div><b>${metrics.brier_score == null ? 'UNAVAILABLE' : metrics.brier_score}</b><small>Brier Score</small></div>`; $('paper-source').textContent=`Bankrollbasis: ${(metrics.bankroll_cents / 100).toFixed(2)} € · ${metrics.closing_line_value}`; }
function renderPaperJournal(bets, metrics) { renderPaperMetrics(metrics); $('paper-journal').innerHTML=bets.length ? bets.map(bet => `<tr><td>${esc(bet.selection)} · ${esc(bet.market)}</td><td>${Number(bet.odds).toFixed(2)}</td><td>${(Number(bet.expected_value) * 100).toFixed(1)}%</td><td>${(Number(bet.stake_cents) / 100).toFixed(2)} €</td><td>${bet.outcome === 'open' ? `<select data-settle="${bet.id}"><option value="open">Offen</option><option value="win">Gewonnen</option><option value="loss">Verloren</option><option value="void">Void</option></select> <button type="button" class="settle" data-bet-id="${bet.id}">Speichern</button>` : esc(bet.outcome)}</td></tr>`).join('') : '<tr><td colspan="5" class="empty">Noch keine Paper-Wetten gespeichert.</td></tr>'; document.querySelectorAll('.settle').forEach(button => button.addEventListener('click', () => settlePaperBet(button.dataset.betId))); }
function csrf() { return document.cookie.split('; ').find(value => value.startsWith('dashboard_csrf='))?.split('=')[1] || ''; }
async function apiJson(url, options) { const response=await fetch(url, options); const data=await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Anfrage fehlgeschlagen'); return data; }
async function savePaperCandidate(event, button) { button.disabled=true; try { await apiJson('/api/betting/paper-bets', {method:'POST', headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()}, body:JSON.stringify({snapshot_id:bettingState.feed.snapshot_id,event_id:event.id,market:event.market,selection:event.selection,bookmaker:event.best_bookmaker,odds:event.market_price,model_probability:event.model_probability,expected_value:event.expected_value})}); await refreshOdds(); } catch (error) { button.textContent=error.message; } finally { button.disabled=false; } }
async function settlePaperBet(id) { const select=document.querySelector(`[data-settle="${id}"]`); if (!select || select.value === 'open') return; try { await apiJson(`/api/betting/paper-bets/${encodeURIComponent(id)}/settle`, {method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()},body:JSON.stringify({outcome:select.value})}); await refreshOdds(); } catch (error) { select.setCustomValidity(error.message); select.reportValidity(); } }
async function refreshOdds() { try { bettingState=await apiJson('/api/betting/state'); const feed=bettingState.feed || {}; liveEvents=feed.status === 'available' ? feed.events : []; renderMarkets(liveEvents); fillCompetitions(); applyFilters(); renderPaperJournal(bettingState.paper_bets || [], bettingState.metrics || {open_bets:0,settled_bets:0,profit_cents:0,roi:null,brier_score:null,bankroll_cents:50000,closing_line_value:'UNAVAILABLE'}); $('odds-status').textContent=feed.status === 'available' ? `VERFÜGBAR · ${liveEvents.length} Events · ${feed.freshness || 'UNAVAILABLE'} · ${feed.snapshot_at || 'UNAVAILABLE'}` : `UNAVAILABLE · ${feed.reason || 'Snapshot fehlt'}`; $('source-status').textContent=feed.status === 'available' ? `The Odds API · Snapshot ${feed.snapshot_id} · Alter ${feed.snapshot_age_seconds ?? 'UNAVAILABLE'} s` : `The Odds API · ${feed.reason || 'Quelle nicht bestätigt'}`; } catch (error) { liveEvents=[]; render([]); $('odds-status').textContent=`UNAVAILABLE · ${error.message}`; $('source-status').textContent='Quelle nicht erreichbar'; } }
function bets() { try { const value=JSON.parse(localStorage.getItem(BETS_KEY) || '[]'); return Array.isArray(value) ? value : []; } catch (_) { return []; } }
function renderBetStats() { const list=bets(), stake=list.reduce((sum, bet) => sum + Number(bet.stake || 0), 0), wins=list.filter(bet => bet.result === 'win').length, losses=list.filter(bet => bet.result === 'loss').length; $('bet-stats').innerHTML=`<div><b>${list.length}</b><small>Einträge</small></div><div><b>${stake.toFixed(2)} €</b><small>Gesamteinsatz</small></div><div><b>${wins}</b><small>Gewonnen</small></div><div><b>${losses}</b><small>Verloren</small></div>`; $('bet-chart').classList.toggle('empty', !list.length); $('bet-chart').textContent=list.length ? 'Verlauf aus lokalen Einträgen · keine Serverdaten' : 'Noch keine lokalen Wetten für Verlauf vorhanden.'; }
$('sport-filter').addEventListener('change', applyFilters); $('competition-filter').addEventListener('change', applyFilters); $('refresh').addEventListener('click', refreshOdds); $('bet-form').addEventListener('submit', event => { event.preventDefault(); const bet={date:$('bet-date').value,sport:$('bet-sport').value.trim(),stake:Number($('bet-stake').value),result:$('bet-result').value}; if (!bet.date || !bet.sport || !Number.isFinite(bet.stake) || bet.stake <= 0) return; localStorage.setItem(BETS_KEY, JSON.stringify([...bets(), bet])); $('bet-message').textContent='Lokal gespeichert. Keine Übertragung.'; event.target.reset(); renderBetStats(); });
renderBetStats(); refreshOdds(); setInterval(refreshOdds, 1800000);
